import "./globals.scss";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
        <link
            href="https://fonts.googleapis.com/css2?family=Neue+Montreal:wght@400;700&display=swap"
            rel="stylesheet"
        />
    </head>
      <body>
        {children}
      </body>
    </html>
  );
}
